image: ghcr.io/xyrisos/xyris-build/xyris-build:3.5.0
aliases:
    # Building
    build: scons -j$(nproc)
    debug: scons -j$(nproc) kernel-debug
    release: scons -j$(nproc) kernel-release
    # Testing
    test:
      script:
        - scons -j$(nproc) tests
        - ./Distribution/Tests/tests
    # Documentation
    docs: scons docs
    # Cleaning
    clean: scons -c
    clean-tests: scons -c tests
    clean-docs: scons -c docs
