from os import walk
from os.path import exists
Import('env')

sources = [
    Glob(path + '/*.cpp') + Glob(path + '/*.c') for (path, name, files) in walk('.')
]

tests = env.Program(
    'tests',
    Flatten([
        Flatten(sources)
    ])
)

Return('tests')
