import os
Import('env')
env.Append(
    CPPDEFINES={
        'ARCH_PAGE_SIZE': 4096,
        'TESTING': None,
    },
)

extensions = [
    '.c',
    '.cpp',
]

sources = env.RecursiveGlob(".", extensions)

tests = env.Program(
    'tests',
    sources,
)

Return('tests')
