#  ____                                        _        _   _
# |  _ \  ___   ___ _   _ _ __ ___   ___ _ __ | |_ __ _| |_(_) ___  _ __
# | | | |/ _ \ / __| | | | '_ ` _ \ / _ \ '_ \| __/ _` | __| |/ _ \| '_ \
# | |_| | (_) | (__| |_| | | | | | |  __/ | | | || (_| | |_| | (_) | | | |
# |____/ \___/ \___|\__,_|_| |_| |_|\___|_| |_|\__\__,_|\__|_|\___/|_| |_|
#
# Compiles the kernel source code located in the kernel folder.

.PHONY: docs
docs:
	@printf "$(COLOR_COM)(DOXYGEN)$(COLOR_NONE)\tGenerating docs\n"
	@doxygen Doxyfile
